tkHotKeyBinder:
  executable: termKeeper.exe

tkExecutable:
  windows:
    activated:
      - Menu
      - Storage
      - Cache
    initialController: Menu
  storage:
    storageFile: storage.xml
  cache:
    cacheFile: cache.xml
    cacheMaxSize: 10